#pragma once
#pragma bank 1

const unsigned char formatted[] = 
"Enter CAIUS"
""
"  CAIUS. Vere is"
"Mistress Page? By"
"gar, I am cozened; I"
"ha'"
"    married un"
"garcon, a boy; un"
"paysan, by gar, a"
"boy; it is"
"    not Anne Page;"
"by gar, I am"
"cozened."
"  MRS. PAGE. Why,"
"did you take her in"
"green?"
"  CAIUS. Ay, be gar,"
"and 'tis a boy; be"
"gar, I'll raise all"
"    Windsor. Exit"
"CAIUS"
"  FORD. This is"
"strange. Who hath"
"got the right Anne?"
"  PAGE. My heart"
"misgives me; here"
"comes Master Fenton."
""
""
"Enter FENTON and"
"ANNE PAGE"
""
"    How now, Master"
"Fenton!"
"  ANNE. Pardon, good"
"father. Good my"
"mother, pardon."
"  PAGE. Now,"
"Mistress, how chance"
"you went not with"
"Master"
"    Slender?"
"  MRS. PAGE. Why"
"went you not with"
"Master Doctor, maid?"
"  FENTON. You do"
"amaze her. Hear the"
"truth of it."
"    You would have"
"married her most"
"shamefully,"
"    Where there was"
"no proportion held"
"in love."
"    The truth is,"
"she and I, long"
"since contracted,"
"    Are now so sure"
"that nothing can"
"dissolve us."
"    Th' offence is"
"holy that she hath"
"committed;"
"    And this deceit"
"loses the name of"
"craft,"
"    Of disobedience,"
"or unduteous title,"
"    Since therein"
"she doth evitate and"
"shun"
"    A thousand"
"irreligious cursed"
"hours,"
"    Which forced"
"marriage would have"
"brought upon her."
"  FORD. Stand not"
"amaz'd; here is no"
"remedy."
"    In love, the"
"heavens themselves"
"do guide the state;"
"    Money buys"
"lands, and wives are"
"sold by fate."
"  FALSTAFF. I am"
"glad, though you"
"have ta'en a special"
"stand"
"    to strike at me,"
"that your arrow hath"
"glanc'd."
"  PAGE. Well, what"
"remedy? Fenton,"
"heaven give thee"
"joy!"
"    What cannot be"
"eschew'd must be"
"embrac'd."
"  FALSTAFF. When"
"night-dogs run, all"
"sorts of deer are"
"chas'd."
"  MRS. PAGE. Well, I"
"will muse no"
"further. Master"
"Fenton,"
"    Heaven give you"
"many, many merry"
"days!"
"    Good husband,"
"let us every one go"
"home,"
"    And laugh this"
"sport o'er by a"
"country fire;"
"    Sir John and"
"all."
"  FORD. Let it be"
"so. Sir John,"
"    To Master Brook"
"you yet shall hold"
"your word;"
"    For he,"
"to-night, shall lie"
"with Mistress Ford."
"Exeunt"
"";