// This file was generated by img2gb, DO NOT EDIT

#include <gb/gb.h>

#ifndef _FONT_TILESET_H
#define _FONT_TILESET_H

extern const uint8_t FONT_TILESET[];
#define FONT_TILESET_TILE_COUNT 48


#endif
